version: "3.17"

services: 
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - python
      - mysql
  python:
    build:
      context: ./dockerfiles
      dockerfile: python.dockerfile
    volumes:
      -./src:/var/www/html
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env